name: Run tests on Windows

on:
  push:
    branches: [ master ]
    paths:
      - '**.py'
      - .github/workflows/tests-windows.yml
      - requirements-test.txt
  pull_request:
    branches: [ master ]
    paths:
      - '**.py'
      - .github/workflows/tests-windows.yml
      - requirements-test.txt

jobs:
  windowstests:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
    env:
      OS: windows-latest
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run test
      run: |
        py.test --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: windows
        env_vars: OS, PYTHON, POSTGRES
        fail_ci_if_error: true
